### PR TITLE
skip files starts with "." in readAllFootersInParallel

### PR DESCRIPTION
**Pull request by SandishKumarHN**
SKIP FILES NAME STARTS WITH "." in parquet.hadoop.ParquetFileReader.readAllFootersInParallel

### CODE REVIEW

**Comment by brockn** [comment]
Hi Sandish,

I think that this is already fixed in the latest version of parquet, see here:

https://github.com/Parquet/parquet-mr/blob/master/parquet-hadoop/src/main/java/parquet/hadoop/ParquetFileReader.java#L305

do you think so as well?

**Comment by SandishKumarHN** [comment]
Hi Brock,

Yes, I see that now. Then I think SQOOP Project has to be updated to latest version of Parquet

**Comment by julienledem** [comment]
parquet development has moved to apache:
https://github.com/apache/parquet-mr
https://issues.apache.org/jira/browse/PARQUET

**Comment by brockn** [comment]
Oops didn't even realize. Yes @SandishKumarHN pls move this to the apache branch.

**Pull request closed without merging**
